/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mitiendacompensar;

import java.awt.Color;
import java.awt.Graphics;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Hember
 */
public class RegistroEmpleados extends javax.swing.JInternalFrame {

    public DefaultTableModel dtm;
    public Object[] registro = new Object[7];
    public int filaSeleccionada = -1;
    public boolean bandera = false;

    public RegistroEmpleados() {
        initComponents();
        dtm = (DefaultTableModel) TblEmpleados.getModel();
    }

    public void paint(Graphics g) {
        super.paint(g);
        if (bandera == true) {

            String tipoJornada;
            int contDiurna = 0;
            int contNocturna = 0;
            for (int count = 0; count < TblEmpleados.getRowCount(); count++) {
                tipoJornada = TblEmpleados.getValueAt(count, 3).toString();
                if (tipoJornada.equals("Diurna")) {
                    contDiurna++;
                } else {
                    contNocturna++;
                }
            }
            
             int gradosDiurna = contDiurna *360 / (contDiurna+contNocturna);
             int gradosNocturna = contNocturna *360 / (contDiurna+contNocturna);

            g.setColor(Color.YELLOW);
            g.fillArc(625, 30, 150, 150, 0, gradosDiurna);
            
            g.setColor(Color.blue);
            g.fillArc(625, 30, 150, 150,gradosDiurna, gradosNocturna);
        }
    }

    /* public void paint(Graphics g) {
        super.paint(g);
        if (bandera == true) {

            String tipo;
            int contDiurna = 0;
            int contNocturna = 0;

            for (int count = 0; count < TblEmpleados.getRowCount(); count++) {
                tipo = TblEmpleados.getValueAt(count, 3).toString();
                if (tipo.equals("Diurna")) {
                    contDiurna++;
                } else {
                    contNocturna++;
                }
            }

            int gradoNocturna = contNocturna * 360 / (contNocturna + contDiurna);
            int gradoDiurna = contDiurna * 360 / (contNocturna + contDiurna);

            g.setColor(Color.BLACK);
            g.fillArc(625, 30, 150, 150, 0, gradoNocturna);
            g.setColor(Color.WHITE);
            g.fillArc(625, 30, 150, 150, gradoNocturna, gradoDiurna);
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        cmbJornada = new javax.swing.JComboBox<>();
        txtTiempo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblEmpleados = new javax.swing.JTable();
        BtnAgregar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnGraficar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Nombre empleado:");

        jLabel2.setText("Identificación:");

        jLabel3.setText("Edad:");

        jLabel4.setText("Jornada:");

        jLabel5.setText("Tiempo Laborado (años):");

        cmbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diurna", "Nocturna" }));

        TblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Identificacion", "Edad", "Jornada", "Tiempo", "Beneficio Tienda", "Beneficio C. Recreacional"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblEmpleados);

        BtnAgregar.setText("Agregar/Modificar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtID)
                            .addComponent(txtEdad)
                            .addComponent(cmbJornada, 0, 216, Short.MAX_VALUE)
                            .addComponent(txtTiempo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGraficar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed

        if (filaSeleccionada == -1) {
            registro[0] = txtNombre.getText();
            registro[1] = txtID.getText();
            registro[2] = Integer.parseInt(txtEdad.getText());
            registro[3] = cmbJornada.getSelectedItem();
            registro[4] = Integer.parseInt(txtTiempo.getText());

            if (Integer.parseInt(txtTiempo.getText()) == 0) {
                registro[5] = "15%";
                registro[6] = "20%";
            } else if (Integer.parseInt(txtTiempo.getText()) >= 1 && Integer.parseInt(txtTiempo.getText()) <= 5) {
                registro[5] = "30%";
                registro[6] = "30%";
            } else if (Integer.parseInt(txtTiempo.getText()) >= 6) {
                registro[5] = "50%";
                registro[6] = "60%";
            }

            dtm.addRow(registro);
        } else {
            TblEmpleados.setValueAt(txtNombre.getText(), filaSeleccionada, 0);
            TblEmpleados.setValueAt(txtID.getText(), filaSeleccionada, 1);
            TblEmpleados.setValueAt(Integer.parseInt(txtEdad.getText()), filaSeleccionada, 2);
            TblEmpleados.setValueAt(cmbJornada.getSelectedItem(), filaSeleccionada, 3);
            TblEmpleados.setValueAt(Integer.parseInt(txtTiempo.getText()), filaSeleccionada, 4);

            if (Integer.parseInt(txtTiempo.getText()) == 0) {
                TblEmpleados.setValueAt("15%", filaSeleccionada, 5);
                TblEmpleados.setValueAt("20%", filaSeleccionada, 6);
            } else if (Integer.parseInt(txtTiempo.getText()) >= 1 && Integer.parseInt(txtTiempo.getText()) <= 5) {
                TblEmpleados.setValueAt("30%", filaSeleccionada, 5);
                TblEmpleados.setValueAt("30%", filaSeleccionada, 6);

            } else if (Integer.parseInt(txtTiempo.getText()) >= 6) {
                TblEmpleados.setValueAt("50%", filaSeleccionada, 5);
                TblEmpleados.setValueAt("60%", filaSeleccionada, 6);
            }
            filaSeleccionada = -1;

        }

       
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void TblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblEmpleadosMouseClicked
        filaSeleccionada = TblEmpleados.getSelectedRow();
        if (filaSeleccionada != -1) {
            txtNombre.setText(TblEmpleados.getValueAt(filaSeleccionada, 0).toString());
            txtID.setText(TblEmpleados.getValueAt(filaSeleccionada, 1).toString());
            txtEdad.setText(TblEmpleados.getValueAt(filaSeleccionada, 2).toString());
            cmbJornada.setSelectedItem(TblEmpleados.getValueAt(filaSeleccionada, 3));
            txtTiempo.setText(TblEmpleados.getValueAt(filaSeleccionada, 4).toString());
        }


    }//GEN-LAST:event_TblEmpleadosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int result = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar el registro?", "Swing Tester",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            dtm.removeRow(TblEmpleados.getSelectedRow());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        /*        bandera = true;
        repaint();*/
        bandera = true;
        repaint();
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JTable TblEmpleados;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JComboBox<String> cmbJornada;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
